substitutions:
    name: "ir2mqtt-002"
    prefix: "homeassistant"

globals:
  - id: name
    type: std::string
    restore_value: no
    initial_value: "\"ir2mqtt-002\""
    
  - id: prefix
    type: std::string
    restore_value: no
    initial_value: "\"homeassistant\""

esphome:
  name: "ir2mqtt-002"

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# https://upk.libretiny.eu/?profile=tuya-generic-universal-ir-remote-control-cbu-v2.0.0

logger:
  level: VERBOSE
  logs:
    mqtt.component: DEBUG
    mqtt.client: ERROR

web_server:

captive_portal:

mdns:

api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

sensor:
  - platform: uptime
    name: Uptime

status_led:
  pin: P24

binary_sensor:
  - platform: gpio
    name: "P6 Pin"
    id: P6_pin
    pin:
      number: P6
      mode: INPUT_PULLUP
      inverted: true

  - platform: gpio
    name: "P7 Pin"
    id: P7_pin
    pin:
      number: P7
      mode: INPUT_PULLUP
      inverted: true

  - platform: gpio
    name: "P8 Pin"
    id: P8_pin
    pin:
      number: P8
      mode: INPUT_PULLUP
      inverted: true

  - platform: gpio
    name: "P9 Pin"
    id: P9_pin
    pin:
      number: P9
      mode: INPUT_PULLUP
      inverted: true

  - platform: gpio
    name: "P24 Pin"
    id: P24_pin
    pin:
      number: P24
      mode: INPUT_PULLUP
      inverted: true

  - platform: gpio
    name: "P26 Pin"
    id: P26_pin
    pin:
      number: P26
      mode: INPUT_PULLUP
      inverted: true

  - platform: gpio
    name: "P28 Pin"
    id: P28_pin
    pin:
      number: P28
      mode: INPUT_PULLUP
      inverted: true

#https://docs.libretiny.eu/boards/generic-bk7231n-qfn32-tuya/#pin-functions