substitutions:
    name: "ir2mqtt-002"
    prefix: "homeassistant"

globals:
  - id: name
    type: std::string
    restore_value: no
    initial_value: "\"ir2mqtt-002\""
    
  - id: prefix
    type: std::string
    restore_value: no
    initial_value: "\"homeassistant\""

esphome:
  name: "ir2mqtt-002"

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# https://upk.libretiny.eu/?profile=tuya-generic-universal-ir-remote-control-cbu-v2.0.0

logger:
  level: VERBOSE
  logs:
    mqtt.component: DEBUG
    mqtt.client: ERROR

web_server:

captive_portal:

mdns:

api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

sensor:
  - platform: uptime
    name: Uptime

status_led:
  pin: P24

output:
  - platform: gpio
    id: p6
    pin: P6
  - platform: gpio
    id: p7
    pin: P7
  - platform: gpio
    id: p8
    pin: P8
  - platform: gpio
    id: p9
    pin: P9
  - platform: gpio
    id: p24
    pin: P24
  - platform: gpio
    id: p26
    pin: P26
  - platform: gpio
    id: p28
    pin: P28

button:
  - platform: restart
    name: Restart

  - platform: template
    name: "Pulse P6"
    on_press:
      - output.turn_on: p6
      - delay: 1s
      - output.turn_off: p6
  - platform: template
    name: "Pulse P7"
    on_press:
      - output.turn_on: p7
      - delay: 1s
      - output.turn_off: p7
  - platform: template
    name: "Pulse P8"
    on_press:
      - output.turn_on: p8
      - delay: 1s
      - output.turn_off: p8
  - platform: template
    name: "Pulse P9"
    on_press:
      - output.turn_on: p9
      - delay: 1s
      - output.turn_off: p9
  - platform: template
    name: "Pulse P24"
    on_press:
      - output.turn_on: p24
      - delay: 1s
      - output.turn_off: p24
  - platform: template
    name: "Pulse P26"
    on_press:
      - output.turn_on: p26
      - delay: 1s
      - output.turn_off: p26
  - platform: template
    name: "Pulse P28"
    on_press:
      - output.turn_on: p28
      - delay: 1s
      - output.turn_off: p28
	  
#https://docs.libretiny.eu/boards/generic-bk7231n-qfn32-tuya/#pin-functions